/*
* qamgen.c
*
* Created: 05.05.2020 16:24:59
*  Author: Chaos
*/ 
#include "avr_compiler.h"
#include "pmic_driver.h"
#include "TC_driver.h"
#include "clksys_driver.h"
#include "sleepConfig.h"
#include "port_driver.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "event_groups.h"
#include "semphr.h"
#include "stack_macros.h"

#include "mem_check.h"

#include "qaminit.h"
#include "qamgen.h"


#define Symbol_00 0x10
#define Symbol_01 0x20
#define Symbol_10 0x40
#define Symbol_11 0x80

#define Data_ready 0x04

#define NR_OF_DATA_SAMPLES 32UL
#define DATABYTETOSENDMASK 0x1F

int16_t symbol_variante = 0;

// test sinus lookup table for 2 periods (=> 2 DMA Channels)
// 1 DMA channel sends data to DAC
// => second DMA channel refill with datas
// const sinus lookup table, do not use it, send idlebits instead
const int16_t sinLookup100[NR_OF_SAMPLES*2] = {	0x0,0x27,0x9c,0x159,0x258,0x38e,0x4f0,0x670,
												0x800,0x990,0xb10,0xc72,0xda8,0xea7,0xf64,0xfd9,
												0xFFF,0xfd9,0xf64,0xea7,0xda8,0xc72,0xb10,0x990,
												0x800,0x670,0x4f0,0x38e,0x258,0x159,0x9c,0x27,
												0x0,0x27,0x9c,0x159,0x258,0x38e,0x4f0,0x670,
												0x800,0x990,0xb10,0xc72,0xda8,0xea7,0xf64,0xfd9,
												0xFFF,0xfd9,0xf64,0xea7,0xda8,0xc72,0xb10,0x990,
												0x800,0x670,0x4f0,0x38e,0x258,0x159,0x9c,0x27};

/*
const lookup tables for all 4 symbols
00 => 100% Amplitude & Phaseshift	0°
01 => 100% Amplitude & Phaseshift  180°
10 =>  50% Amplitude & Phaseshift	0°
11 =>  50% Amplitude & Phaseshift  180°
MSB = Amplitude | LSB = Phaseshift
=> Generated by https://www.daycounter.com/Calculators/Sine-Generator-Calculator.phtml

calucalted offset offset
0x0,0x14,0x4e,0xad,0x12c,0x1c7,0x278,0x338,
0x400,0x4c8,0x588,0x639,0x6d4,0x753,0x7b2,0x7ec,
0x800,0x7ec,0x7b2,0x753,0x6d4,0x639,0x588,0x4c8,
0x400,0x338,0x278,0x1c7,0x12c,0xad,0x4e,0x14
=
0x400,0x414,0x44e,0x4ad,0x52c,0x5c1,0x678,0x738,
0x800,0x8c8,0x988,0xa39,0xad4,0xb53,0xbb2,0xbec,
0xc00,0xbec,0xbb2,0xb53,0xad4,0xa39,0x988,0x8c8,
0x800,0x738,0x678,0x5c1,0x52c,0x4ad,0x44e,0x414
*/

const int16_t Symbol_00_lookup[NR_OF_SAMPLES] = {	
											0x0,0x27,0x9c,0x159,0x258,0x38e,0x4f0,0x670,
											0x800,0x990,0xb10,0xc72,0xda8,0xea7,0xf64,0xfd9,
											0xFFF,0xfd9,0xf64,0xea7,0xda8,0xc72,0xb10,0x990,
											0x800,0x670,0x4f0,0x38e,0x258,0x159,0x9c,0x27,
											};
										
const int16_t Symbol_01_lookup[NR_OF_SAMPLES] = {	
											0xFFF,0xfd9,0xf64,0xea7,0xda8,0xc72,0xb10,0x990,
											0x800,0x670,0x4f0,0x38e,0x258,0x159,0x9c,0x27,
											0x0,0x27,0x9c,0x159,0x258,0x38e,0x4f0,0x670,
											0x800,0x990,0xb10,0xc72,0xda8,0xea7,0xf64,0xfd9,
											};

const int16_t Symbol_10_lookup[NR_OF_SAMPLES] = {	
											0x400,0x414,0x44e,0x4ad,0x52c,0x5c1,0x678,0x738,
											0x800,0x8c8,0x988,0xa39,0xad4,0xb53,0xbb2,0xbec,
											0xc00,0xbec,0xbb2,0xb53,0xad4,0xa39,0x988,0x8c8,
											0x800,0x738,0x678,0x5c1,0x52c,0x4ad,0x44e,0x414
											};	

const int16_t Symbol_11_lookup[NR_OF_SAMPLES] = {	
											0xc00,0xbec,0xbb2,0xb53,0xad4,0xa39,0x988,0x8c8,
											0x800,0x738,0x678,0x5c1,0x52c,0x4ad,0x44e,0x414,
											0x400,0x414,0x44e,0x4ad,0x52c,0x5c1,0x678,0x738,
											0x800,0x8c8,0x988,0xa39,0xad4,0xb53,0xbb2,0xbec
											};

// const Idle Bit's
const uint8_t Idle_bits_1 = 0b01;
const uint8_t Idle_bits_2 = 0b10;

// const Sync bits
const uint8_t Sync_bits = 0b11;

// test lenght bits
const uint8_t Length_bits[] = {01,00};


typedef enum {
	Idle_1,
	Idle_2,
	SyncByte,
	Length,
	Datas,
	Checksum	
} eProtokollStates;

TaskHandle_t xsendSymbol;

EventGroupHandle_t xQAMchannel;

QueueHandle_t xQueueData;
QueueHandle_t xSymbolQueue;



void vQuamGen(void *pvParameters) {
	while(evDMAState == NULL) {
		vTaskDelay(3/portTICK_RATE_MS);
	}
	xEventGroupWaitBits(evDMAState, DMAGENREADY, false, true, portMAX_DELAY);
	
	xQAMchannel=xEventGroupCreate();
	 
	xQueueData		= xQueueCreate(1, sizeof(uint8_t)*NR_OF_DATA_SAMPLES);
	xSymbolQueue	= xQueueCreate(20, sizeof(uint8_t)); 
	
	xTaskCreate(vsendSymbol, NULL, configMINIMAL_STACK_SIZE+400, NULL, 2, &xsendSymbol);
	
	for(;;) {
		vTaskDelay(10/portTICK_RATE_MS);
		
	}
}

void fillBuffer(uint16_t buffer[NR_OF_SAMPLES]) {
	uint8_t EventGroupBits= xEventGroupGetBitsFromISR(xQAMchannel);	
	uint8_t	Rx_Symbol;
	
	xQueueReceiveFromISR(xSymbolQueue, (void*)&Rx_Symbol,NULL );
	
	switch(Rx_Symbol){
		case 0b00000000:{
			for(int i = 0; i < NR_OF_SAMPLES;i++) {
					buffer[i] = Symbol_00_lookup[i];
				}
		break;
		}
		case 0b00000001:{
			for(int i = 0; i < NR_OF_SAMPLES;i++) {
				buffer[i] = Symbol_01_lookup[i];
			}
			break;
		}
		case 0b00000010:{
			for(int i = 0; i < NR_OF_SAMPLES;i++) {
				buffer[i] = Symbol_10_lookup[i];
			}
			break;
		}
		case 0b00000011:{
			for(int i = 0; i < NR_OF_SAMPLES;i++) {
				buffer[i] = Symbol_11_lookup[i];
			}
			break;
		}

	}//switch
	// set Eventgroup-bit to indicate buffer is full
	xEventGroupSetBits(xQAMchannel,Data_ready); 
}// end void fillbuffer

ISR(DMA_CH0_vect)
{
	//static signed BaseType_t test;	
	DMA.CH0.CTRLB|=0x10;
	fillBuffer(&dacBuffer0[0]);
}

ISR(DMA_CH1_vect)
{
	DMA.CH1.CTRLB|=0x10;
	fillBuffer(&dacBuffer1[0]);
}

void vsendCommand( uint8_t Data[]){
	if(xQueueData != 0){
		xQueueSend(xQueueData, (void*)Data, pdMS_TO_TICKS(10));
	}
}// end void send command


void vsendSymbol(void *pvParameters){
	(void) pvParameters;
	// init values
	
	bool Datas_rdy_to_send = false;
	uint8_t DataSymbolToSend; 
	uint8_t DataSymbolCounter; 
	uint8_t LenghtSymbolCounter;
	uint8_t Data[NR_OF_DATA_SAMPLES +1] = {}; 
	
	eProtokollStates Protokoll = Idle_1;
	
	
	for(;;){
		switch(Protokoll){
			case Idle_1: {
				// send first idlebits -> Symbol 01
				if( xSymbolQueue != 0){
					if(xQueueSend(xSymbolQueue, (void*) &Idle_bits_1, (TickType_t) 10) != pdPASS){
						// failed to send to queue
					}
				}
				
				Protokoll = Idle_2;
				break;	
			}// end case Idle1 
			
			case Idle_2: {
				// send second Idlebits -> Symbol 10
				if( xSymbolQueue != 0){
					if(xQueueSend(xSymbolQueue, (void*) &Idle_bits_2, (TickType_t) 10) != pdPASS){
						// failed to send to queue
					}
				}
				
				// check if Datas are avaiable to send
				// if not => next state Idle_1
				if( uxQueueMessagesWaiting(xQueueData != 0)) {
					Protokoll = SyncByte;
				}
				else{
					Protokoll = Idle_1;
				}
				break;
			}// end case Idle2
			
			case SyncByte: {
				// send sync bits -> Symbol 11
				if( xSymbolQueue != 0){
					if(xQueueSend(xSymbolQueue, (void*) &Sync_bits, (TickType_t) 10) != pdPASS){
						// failed to send to queue
					}
				}
								
				Protokoll = Length;
				break;
			}// end case SyncBites
			
			case Length: {
				//send length (bits or symbol? -> TBD)
				if( LenghtSymbolCounter <= 1){
					if( xSymbolQueue != 0){
						if(xQueueSend(xSymbolQueue, (void*) &Length_bits[LenghtSymbolCounter], (TickType_t) 10) != pdPASS){
							// failed to send to queue
						}
						LenghtSymbolCounter++;
					}
				}				
				Protokoll = Datas;
				LenghtSymbolCounter = 0;
				break;
			}// end case Length
			
			case Datas: {
				//rx data
				if (xQueueReceive(xQueueData, Data, pdMS_TO_TICKS(0)) == pdTRUE){
					DataSymbolToSend = Data[0] & DATABYTETOSENDMASK;
				
				// send data symbol
				if(DataSymbolCounter <= 3){
					xQueueReceive(xQueueData, Data, pdMS_TO_TICKS(0))
					DataSymbolToSend = Data[DataSymbolCounter];
					if( xSymbolQueue != 0){
						if(xQueueSend(xSymbolQueue, (void*) &Length_bits[LenghtSymbolCounter], (TickType_t) 10) != pdPASS){
							// failed to send to queue
						}
						DataSymbolCounter++;
					}
				}
				DataSymbolCounter = 0;
				Protokoll = Checksum;
				break;
			}// end case Datas
			
			
			case Checksum: {
				
				
				// after sendin Ckecksum => start again with IDLE bits
				Protokoll = Idle_1;
				break;
			}// end case Checksum			
		}// end switch	
		
		// Data send part
		
		
			
	}// end for	
}// end void sendSymbol